stages:
- name: Build docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api-poc
  when:
    branch:
      include:
      - main
timeout: 60
notification: {}
