name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Loging to GitHub Package Registry
        run: |
          docker login -u ${{ secrets.HUB_USERNAME }} -p ${{ secrets.PASSWORD }} https://index.docker.io/v1
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/swapnil13cs56/tcp-test-registry:v1'
          format: 'sarif'
          output: 'trivy-results.sarif'
#         env:
#           TRIVY_USERNAME: HUB_USERNAME
#           TRIVY_PASSWORD: HUB_PASSWORD
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
